# Generated by Django 5.2.14 on 2026-05-30 20:45

from django.db import migrations
from django.db.models import Count


def init_ref_produits(apps, schema_editor):
    Product = apps.get_model('base', 'product')
    Provider = apps.get_model('base', 'provider')

    for provider in Provider.objects.all():
        # Collect all active referents of all active products
        referents = Product.objects.filter(
            activated=True,
            provider=provider,
            referent__isnull=False,
            referent__household__activated=True,
        ).order_by(
            'referent'
        ).values('referent').annotate(
            reference_count=Count('id', unique=True),
        ).distinct()
        if referents:
            # Select the members that have the max of provider products under their responsibility…
            max_refs = max([row['reference_count'] for row in referents])
            elected_members_ids = referents.filter(reference_count=max_refs).values_list('referent', flat=True)
            non_elected_members_ids = referents.exclude(reference_count=max_refs).values_list('referent', flat=True)
            print(f"Ont été élus comme référents fournisseur de {provider.name} : {elected_members_ids}")
            print(f"Ont été gardes comme référents de certains produits de {provider.name} : {non_elected_members_ids}")

            # Set elected member(s) as provider referent…
            provider.referents.set(elected_members_ids)
            # And remove them as product referent (to avoid double notice)
            Product.objects.filter(
                referent__id__in=elected_members_ids,
                provider=provider,
            ).update(
                referent=None,
            )

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_provider_referents"),
    ]

    operations = [
        migrations.RunPython(init_ref_produits)  # Irreversible
    ]

